# Generated by Django 3.1.5 on 2021-12-09 09:48

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=30, verbose_name='Полное имя отдела')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator_department', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='MainTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cols_subtasks', models.IntegerField(default=0, null=True, verbose_name='Колличество подзадач')),
                ('task_name', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('full_link', models.CharField(max_length=150, verbose_name='Путь до задачи')),
                ('date_finished', models.DateField(blank=True, null=True, verbose_name='Дата окончания задачи')),
                ('about', models.TextField(default='', max_length=200, verbose_name='Подробности')),
                ('location', models.CharField(default='', max_length=100, verbose_name='Местоположение')),
                ('is_active', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('connected_workers', models.ManyToManyField(blank=True, related_name='workers_main', to=settings.AUTH_USER_MODEL)),
                ('creator_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator_task', to=settings.AUTH_USER_MODEL)),
                ('executor_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor_task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintasks',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, max_digits=3, null=True, unique=True, verbose_name='Код объекта')),
                ('shortname', models.CharField(default='', max_length=8, unique=True, verbose_name='Сокращённое имя объекта')),
                ('fullname', models.CharField(default='', max_length=25, verbose_name='Полное имя объекта')),
                ('supervisor', models.CharField(default='', max_length=30, verbose_name='Руководитель проекта')),
                ('chief', models.CharField(default='', max_length=30, verbose_name='Начальник участка')),
                ('group_number', models.DecimalField(decimal_places=0, max_digits=5, null=True, unique=True, verbose_name='Номер проектной группы')),
                ('date_finished', models.DateField(blank=True, null=True, verbose_name='Дата сдачи объекта')),
                ('date_start_document', models.DateField(blank=True, null=True, verbose_name='Дата создания ТУ Электоснабжение')),
                ('date_finished_document', models.DateField(blank=True, null=True, verbose_name='Дата окончания ТУ Электоснабжение')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('connected_workers', models.ManyToManyField(blank=True, related_name='workers_object', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_limba', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Заголовок')),
                ('body', models.CharField(default='', max_length=400, verbose_name='Сообщение')),
                ('data', models.CharField(default='', max_length=600, verbose_name='Данные')),
                ('type', models.DecimalField(decimal_places=0, default=0, max_digits=1, verbose_name='Тип сообщения')),
                ('is_active', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'push_notifications',
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('full_link', models.CharField(max_length=150, verbose_name='Путь до задачи')),
                ('date_finished', models.DateField(blank=True, null=True, verbose_name='Дата окончания задачи')),
                ('about', models.TextField(default='', max_length=200, verbose_name='Подробности')),
                ('location', models.CharField(default='', max_length=100, verbose_name='Местоположение')),
                ('is_active', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('connected_workers', models.ManyToManyField(blank=True, related_name='workers_sub', to=settings.AUTH_USER_MODEL)),
                ('executor_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor', to=settings.AUTH_USER_MODEL)),
                ('maintask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintask', to='main.maintask')),
            ],
            options={
                'db_table': 'subtasks',
            },
        ),
        migrations.CreateModel(
            name='UserAdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(default='', max_length=3, verbose_name='Аббревиатура ФИО')),
                ('position_worker', models.CharField(choices=[('0', 'Администратор'), ('1', 'Руководитель проектов'), ('2', 'Начальник отдела'), ('3', 'Начальник участка'), ('4', 'Прораб'), ('5', 'Монтажник'), ('6', 'Инженер')], default=6, max_length=1, verbose_name='Должность работника')),
                ('type_user', models.DecimalField(decimal_places=0, default=2, max_digits=1, verbose_name='Тип пользователя')),
                ('code_fcm', models.CharField(default='', max_length=300, verbose_name='Токен пользователя')),
                ('index_color', models.DecimalField(decimal_places=0, default=0, max_digits=1, verbose_name='Цвет иконки пользователя')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UploadFileSubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=main.models.upload_path_files_subtask)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('subtask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask_file', to='main.subtask')),
            ],
            options={
                'db_table': 'subtask_files',
            },
        ),
        migrations.CreateModel(
            name='UploadFileObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=main.models.upload_path_files_to_object)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_file', to='main.object')),
            ],
            options={
                'db_table': 'object_files',
            },
        ),
        migrations.CreateModel(
            name='UploadFileMainTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=main.models.upload_path_files_maintask)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintask_file', to='main.maintask')),
            ],
            options={
                'db_table': 'maintask_files',
            },
        ),
        migrations.CreateModel(
            name='SubTaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', max_length=100, verbose_name='Комментарий')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('creator_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator_subcomment', to=settings.AUTH_USER_MODEL)),
                ('subtask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask_comment', to='main.subtask')),
            ],
            options={
                'db_table': 'subtask_comment',
            },
        ),
        migrations.CreateModel(
            name='SubDepartmentObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=30, verbose_name='Полное имя подобъекта')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator_subdepartment', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='main.department')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_executor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subdepartment_objects',
                'unique_together': {('department', 'fullname')},
            },
        ),
        migrations.CreateModel(
            name='MainTaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', max_length=100, verbose_name='Комментарий')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('creator_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator_maincomment', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintask_comment', to='main.maintask')),
            ],
            options={
                'db_table': 'maintask_comment',
            },
        ),
        migrations.AddField(
            model_name='maintask',
            name='subdepartment_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_object', to='main.subdepartmentobject'),
        ),
        migrations.CreateModel(
            name='ImageSubTaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=main.models.upload_path_sub_comment, verbose_name='Фотография')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('comment_subtask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subimage_comment', to='main.subtaskcomment')),
            ],
            options={
                'db_table': 'subimage_comment',
            },
        ),
        migrations.CreateModel(
            name='ImageSubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=main.models.upload_path_sub, verbose_name='Фотография')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('subtask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask_img', to='main.subtask')),
            ],
            options={
                'db_table': 'subimage',
            },
        ),
        migrations.CreateModel(
            name='ImageObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=main.models.upload_path_object, verbose_name='Фотография')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_img', to='main.object')),
            ],
            options={
                'db_table': 'objectimage',
            },
        ),
        migrations.CreateModel(
            name='ImageMainTaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=main.models.upload_path_main_comment, verbose_name='Фотография')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('comment_maintask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainimage_comment', to='main.maintaskcomment')),
            ],
            options={
                'db_table': 'mainimage_comment',
            },
        ),
        migrations.CreateModel(
            name='ImageMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=main.models.upload_path_main, verbose_name='Фотография')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintask_img', to='main.maintask')),
            ],
            options={
                'db_table': 'imagemain',
            },
        ),
        migrations.CreateModel(
            name='FileSubTaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=main.models.upload_path_files_subtask_comment)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('comment_subtask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_subtask_comment', to='main.subtaskcomment')),
            ],
            options={
                'db_table': 'files_subtask_comment',
            },
        ),
        migrations.CreateModel(
            name='FileMainTaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=main.models.upload_path_files_maintask_comment)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('comment_maintask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_maintask_comment', to='main.maintaskcomment')),
            ],
            options={
                'db_table': 'files_maintask_comment',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='object_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object', to='main.object'),
        ),
        migrations.AddField(
            model_name='department',
            name='user_assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_assign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('object_name', 'fullname')},
        ),
    ]
