# Generated by Django 3.1.5 on 2021-11-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='fullname',
            field=models.CharField(default='', max_length=25, verbose_name='Полное имя объекта'),
        ),
    ]
