# Generated by Django 3.2.8 on 2021-11-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalinfo',
            name='index_color',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, verbose_name='Цвет иконки пользователя'),
        ),
    ]
