# Generated by Django 3.2.7 on 2021-10-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalinfo',
            name='code_fcm',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='full_link',
            field=models.CharField(max_length=150, verbose_name='Путь до задачи'),
        ),
        migrations.AlterField(
            model_name='object',
            name='fullname',
            field=models.CharField(default='', max_length=15, verbose_name='Полное имя объекта'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='full_link',
            field=models.CharField(max_length=150, verbose_name='Путь до задачи'),
        ),
    ]
