# Generated by Django 3.1.5 on 2021-11-02 08:53

import Main.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20211101_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=Main.models.upload_path_object, verbose_name='Фотография')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_img', to='Main.object')),
            ],
            options={
                'db_table': 'objectimage',
            },
        ),
    ]
