# Generated by Django 3.2.9 on 2021-11-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pushnotification_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintask',
            name='about',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='about',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Местоположение'),
        ),
    ]
