# Generated by Django 3.2.7 on 2021-10-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20211013_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='code_fcm',
            field=models.CharField(default='', max_length=300, verbose_name='Токен пользователя'),
        ),
    ]
