# Generated by Django 3.1.5 on 2021-11-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211116_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.CharField(max_length=400, verbose_name='Сообщение')),
                ('data', models.CharField(max_length=600, verbose_name='Данные')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'push_notifications',
            },
        ),
    ]
