# Generated by Django 3.2.9 on 2021-12-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211123_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalinfo',
            name='type_system',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, verbose_name='Тип системы'),
        ),
    ]
