# Generated by Django 3.1.5 on 2021-12-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211215_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintask',
            name='object',
            field=models.CharField(default='', max_length=20, verbose_name='Объект'),
        ),
    ]
