# Generated by Django 3.1.5 on 2021-11-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='type',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, verbose_name='Тип сообщения'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='body',
            field=models.CharField(default='', max_length=400, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='data',
            field=models.CharField(default='', max_length=600, verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
        ),
    ]
