# Generated by Django 3.2.9 on 2021-12-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_useradditionalinfo_type_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintask',
            name='object',
            field=models.DecimalField(decimal_places=0, default=999999, max_digits=6, verbose_name='Объект'),
        ),
    ]
