# Generated by Django 3.1.5 on 2021-12-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_maintask_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintask',
            name='is_show_executor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtask',
            name='is_show_executor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtask',
            name='object',
            field=models.CharField(default='', max_length=20, verbose_name='Объект'),
        ),
    ]
