# Generated by Django 3.2.4 on 2021-12-06 08:29

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211123_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileMainTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=main.models.upload_path_files_maintask)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintask_file', to='main.maintask')),
            ],
        ),
    ]
