# Generated by Django 3.2.4 on 2021-12-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_uploadfilemaintask'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadfilemaintask',
            table='maintask_files',
        ),
    ]
