# Generated by Django 3.2.9 on 2021-12-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_filemaintaskcomment_filesubtaskcomment_uploadfilemaintask_uploadfileobject_uploadfilesubtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemaintaskcomment',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filesubtaskcomment',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfilemaintask',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfileobject',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfilesubtask',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
