# Generated by Django 3.2.4 on 2021-12-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_uploadfilemaintask_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfilemaintask',
            old_name='title',
            new_name='name_file',
        ),
    ]
