# Generated by Django 4.0 on 2021-12-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211207_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemaintaskcomment',
            name='size',
        ),
        migrations.RemoveField(
            model_name='filesubtaskcomment',
            name='size',
        ),
        migrations.RemoveField(
            model_name='uploadfilemaintask',
            name='size',
        ),
        migrations.RemoveField(
            model_name='uploadfileobject',
            name='size',
        ),
        migrations.RemoveField(
            model_name='uploadfilesubtask',
            name='size',
        ),
        migrations.RemoveField(
            model_name='useradditionalinfo',
            name='type_system',
        ),
        migrations.AddField(
            model_name='maintask',
            name='is_show_executor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtask',
            name='is_show_executor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtask',
            name='object',
            field=models.CharField(default='', max_length=10, verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='bearer_token',
            field=models.CharField(default='', max_length=300, verbose_name='Токен авторизации'),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='about',
            field=models.TextField(default='', max_length=200, verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='object',
            field=models.CharField(default='', max_length=10, verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='about',
            field=models.TextField(default='', max_length=200, verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Местоположение'),
        ),
    ]
