# Generated by Django 4.0 on 2021-12-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_filemaintaskcomment_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='subdepartment_object',
            field=models.CharField(default='', max_length=10, verbose_name='Отдел'),
        ),
    ]
