# Generated by Django 4.0 on 2021-12-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subtask_subdepartment_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalinfo',
            name='type_system',
            field=models.CharField(default='', max_length=1, verbose_name='Тип устройства'),
        ),
    ]
