# Generated by Django 4.0 on 2021-12-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_useradditionalinfo_type_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Заголовок')),
                ('body', models.CharField(default='', max_length=400, verbose_name='Сообщение')),
                ('data', models.CharField(default='', max_length=600, verbose_name='Данные')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_push', to='main.user')),
            ],
            options={
                'db_table': 'push_notifications_user',
            },
        ),
    ]
