# Generated by Django 4.0 on 2021-12-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pushnotificationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='token_fcm',
            field=models.CharField(default='', max_length=300, verbose_name='Токен fcm'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='type_system',
            field=models.CharField(default='', max_length=1, verbose_name='Тип устройства'),
        ),
    ]
