# Generated by Django 4.0 on 2021-12-23 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pushnotification_token_fcm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintask',
            name='connected_workers',
            field=models.ManyToManyField(blank=True, null=True, related_name='workers_main', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='object',
            name='connected_workers',
            field=models.ManyToManyField(blank=True, null=True, related_name='workers_object', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='connected_workers',
            field=models.ManyToManyField(blank=True, null=True, related_name='workers_sub', to=settings.AUTH_USER_MODEL),
        ),
    ]
