# Generated by Django 4.0 on 2021-12-24 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_maintask_connected_workers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintask',
            name='about',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='connected_workers',
            field=models.ManyToManyField(blank=True, related_name='workers_main', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='object',
            name='connected_workers',
            field=models.ManyToManyField(blank=True, related_name='workers_object', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='about',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='connected_workers',
            field=models.ManyToManyField(blank=True, related_name='workers_sub', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Местоположение'),
        ),
    ]
