# Generated by Django 4.0 on 2021-12-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_maintask_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='chief',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Начальник участка'),
        ),
        migrations.AlterField(
            model_name='object',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Полное имя объекта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='supervisor',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Руководитель проекта'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='token_fcm',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Токен fcm'),
        ),
    ]
