# Generated by Django 4.0 on 2021-12-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_object_is_new_task_object_number_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='is_new_task',
        ),
        migrations.RemoveField(
            model_name='object',
            name='number_tasks',
        ),
    ]
