# Generated by Django 4.0 on 2022-01-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_subdepartmentobject_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdepartmentobject',
            name='object_id',
        ),
    ]
