db:
	python3 manage.py migrate --run-syncdb
mig:
	python3 manage.py makemigrations && python3 manage.py migrate
run:
	python3 manage.py runserver 172.22.2.181:8000
	# python3 manage.py runserver 192.168.0.77:8005
	# python3 manage.py runserver 172.22.2.141:8000
	# python3 manage.py runserver 192.168.0.252:8000
user:
	python3 manage.py createsuperuser
new:
	python3 manage.py makemigrations Main
